### ISSUE TITLE
register 0.2.0

### ISSUE THREAD

**Issue by JeffFessler** [ahwillia/NonNegLeastSquares.jl#24]
@JuliaRegistrator register()

**Comment by MatFi** [comment]
is the [Registrator app](https://github.com/JuliaRegistries/Registrator.jl#via-the-github-app) installed?

**Comment by JeffFessler** [comment]
doh.  apparently not.  i did that so long ago on my own github page that i forgot about that step.
probably only the owner can do it.
@ahwillia can you please click on this to set it up:
https://github.com/apps/juliateam-registrator/installations/new

**Comment by ahwillia** [comment]
@JuliaRegistrator register()

**Comment by ahwillia** [comment]
Looks like that worked, but let me know if there's more steps I need to do.

**Comment by JeffFessler** [comment]
yay!  now we must wait 3 days (for any new package).  it didn't complain about compat so that seems ok.
