### ISSUE TITLE
CI.yml fails due to python issue

### ISSUE THREAD

**Issue by JeffFessler** [ahwillia/NonNegLeastSquares.jl#27]
I was hoping to use github actions to do unit tests and code coverage, but `runtests` fails with github actions due to some PyCall issue:

https://github.com/ahwillia/NonNegLeastSquares.jl/actions/runs/681382850

I don't know enough about PyCall to work on that...

edit: it fails on ubuntu but passes on mac and windows.  huh.

**Comment by JeffFessler** [comment]
well, at least codecov is working now, so anyone who wants to improve coverage can see where to start.

**Comment by MatFi** [comment]
Copy pasted two lines from [NNLS.jl](https://github.com/ahwillia/NonNegLeastSquares.jl/commit/fed55e140a996ef00a7b7e78c6824c100ca93ea4) to https://github.com/ahwillia/NonNegLeastSquares.jl/commit/fed55e140a996ef00a7b7e78c6824c100ca93ea4 solved the PyCall problem.
