### ISSUE TITLE
MLJ interface

### ISSUE THREAD

**Issue by olivierlabayle** [ahwillia/NonNegLeastSquares.jl#33]
Hi,

I will need a NNLS implementation in a project I'm working on and I noticed you provide an implementation here. I'm also using the [MLJ](https://alan-turing-institute.github.io/MLJ.jl/dev/adding_models_for_general_use/) framework and would need to interface with that. I haven't looked in details at your `nonneg_lsq` interface but it would probably mean having a light MLJ interface on top of it. I'm happy to do it and contribute to your package if this is something you would like included. It would basically mean an extra dependency on `MLJModelInterface`. Please let me know your thoughts.

Olivier

**Comment by JeffFessler** [comment]
Hi Olivier, I am just a "helper" here, not a "decider" but maybe I can start with a query.  I didn't know about the MLJ package - it is impressively extensive!  I am wondering though why an *optimization* package like NNLS would need an MLJ dependence?  The list of 3rd party packages using MLJ are all *models*, not optimization methods and certainly using MLJ there makes sense.  NNLS does not have any models in it.  Would you mind elaborating on the possible need for the dependence and the benefit?   It might help the "deciders" :)
BTW, the `nonneg_lsq` interface uses "duck typing" for `A` and `B` so it should be able to handle quite general types.  Perhaps it will work out-of-the-box for your use case?  And if not, perhaps we should first find out why not and see if we can address it here in a more generalizable way?

**Comment by olivierlabayle** [comment]
Hi Jeff, thanks for your comment. Indeed, it may not seem natural for the package to depend on the MLJInterface package. It probably depends if the "deciders" (as you say ;) ) have any interest in targeting the machine learning community. At the end of the day most machine learning algorithms are optimization methods. Maybe something which is not clear from my message is that I only intend to add a small wrapper around `nonneg_lsq` to later on allow the MLJ community to build models using `nonneg_lsq` under the hood. I must also say I've already made some progress on this especially because the `nonneg_lsq` is already a good interface and nothing much remains to do :). I can understand if it's not part of your development plans and also have the possibility to write a separate package depending on both **MLJInterface** and **NonNegLeastSquares**.

**Comment by JeffFessler** [comment]
I personally would be quite interested to see what that wrapper looks like, regardless of what happens here.
Perhaps you could provide a url (or PR) when ready?

To orient myself I looked at the dependencies of a couple big-name numerical optimization packages for Julia and neither of them depend on MLJ, so it may make sense to have the wrapper in a higher level package.
https://github.com/JuliaNLSolvers/Optim.jl/blob/master/Project.toml
https://github.com/JuliaOpt/NLopt.jl/blob/master/Project.toml

Out of curiosity I followed a suggestion here https://www.reddit.com/r/Julia/comments/bkzwmq/dependency_graph_and_lookup/
and searched for registered packages that depend on `MLJModelInterface` and found this list:

./B/BetaML/Deps.toml
./E/Econometrics/Deps.toml
./E/EvoTrees/Deps.toml
./F/Fairness/Deps.toml
./G/GeoLearning/Deps.toml
./G/GeoStatsBase/Deps.toml
./H/HealthMLBase/Deps.toml
./L/LightGBM/Deps.toml
./M/MCMCChains/Deps.toml
./M/MLJBase/Deps.toml
./M/MLJClusteringInterface/Deps.toml
./M/MLJDecisionTreeInterface/Deps.toml
./M/MLJFlux/Deps.toml
./M/MLJGLMInterface/Deps.toml
./M/MLJLIBSVMInterface/Deps.toml
./M/MLJLinearModels/Deps.toml
./M/MLJModels/Deps.toml
./M/MLJMultivariateStatsInterface/Deps.toml
./M/MLJNaiveBayesInterface/Deps.toml
./M/MLJScikitLearn/Deps.toml
./M/MLJScikitLearnInterface/Deps.toml
./M/MLJSerialization/Deps.toml
./M/MLJTuning/Deps.toml
./M/MLJXGBoostInterface/Deps.toml
./N/NearestNeighborModels/Deps.toml
./O/OutlierDetection/Deps.toml
./P/ParallelKMeans/Deps.toml
./P/PartialLeastSquaresRegressor/Deps.toml
./P/PersistenceDiagrams/Deps.toml
./R/Ripserer/Deps.toml
./S/SigmaRidgeRegression/Deps.toml
./S/SossMLJ/Deps.toml

Note to self
`grep --recursive --binary-files=without-match -l MLJModelInte | grep Deps | sort`

**Comment by ahwillia** [comment]
I don't have any objections as long as someone is able to keep this interface up to date and maintained over time

**Comment by MatFi** [comment]
Agree with @JeffFessler. While it's generally a good thing to expand the audience, heavy dependencies will not only raise the maintenance issue, but could also annoy existing users (me for example). A wrapper package is the solution we should aim for and mention its existence in the readme.

**Comment by olivierlabayle** [comment]
Allright, no problem, I'll go for the 2nd option then and let you reference if you wish! Thanks for your answers.

For those interested like Jeff, the simplest interface could look like this : https://github.com/olivierlabayle/NonNegLeastSquaresMLJInterface.jl/blob/mljinterface/src/NonNegLeastSquaresMLJInterface.jl

I close the issue!

**Comment by JeffFessler** [comment]
Thanks, and please let us know when your interface is stable and we'll update the Readme.

Note that `nonneg_lsq` has a lot of different method options, so I'd recommend trying to expose those (via `kwargs...`?)
in your `MLJModelInterface.fit` routine, if its API allows that.  (In my view the jury is still out on which of the methods is the fastest and it probably depends on the application anyway.)
I'm focusing on this (currently option-less) line: `fitresult = vec(nonneg_lsq(X, y))`
