### ISSUE TITLE
Block principal pivoting method is missing step 5 from Algorithm 2 of Kim & Park (2011)

### ISSUE THREAD

**Issue by brossetti** [ahwillia/NonNegLeastSquares.jl#9]
`pivot_comb()` can crash with a `BoundsError` because step 5 from Algorithm 2 of Kim & Park (2011) is missing. This can be resolved by adding a check between [lines 55 and 56](https://github.com/ahwillia/NonNegLeastSquares.jl/blob/acbb191ca2d0b06d6f042512393b00df5d53a1a0/src/pivot_comb.jl#L55-L56) that skips any iteration where `nV == 0`. I'm happy to submit a pull request if this project is still active.

**Comment by ahwillia** [comment]
Thanks! Happy to review and merge this. Nothing is in active development,
but I will keep this going as a basic resource.
